languageCode: id-id
title: Farrel Franqois Blog
paginate: 5
enableEmoji: false
enableInlineShortcodes: true
enableGitInfo: true
content-dir: content
timeout: 1200000
timeZone: Asia/Jakarta

defaultContentLanguage: id

ignoreFiles:
  - README.md

permalinks:
  post: /:slug/
  page: /:slug/
  tags: /tag/:slug/
  categories: /kategori/:slug/

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  tableOfContents:
    start: 1
    end: 4
    ordered: true
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false
