main = [ ]

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/FarrelF"
weight = -100

[social.params]
icon = "brand-github"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/FarrelFranqois"
weight = -80

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "x"
name = "X (sebelumnya Twitter)"
url = "https://x.com/FarrelFranqois"
weight = -60

[social.params]
icon = "brand-x"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/FarrelF"
weight = -40

[social.params]
icon = "brand-telegram"
