
main:
  - identifier: home
    name: Beranda
    url: /
    weight: -100
    params:
      icon: home

social:
  - identifier: github
    name: GitHub
    url: https://github.com/FarrelF/Blog
    weight: -100
    params:
      icon: brand-github

  - identifier: facebook
    name: Facebook
    url: https://www.facebook.com/FarrelFranqois
    weight: -80
    params:
      icon: brand-facebook

  - identifier: twitter
    name: Twitter
    url: https://twitter.com/FarrelFranqois
    weight: -60
    params:
      icon: brand-twitter

  - identifier: telegram
    name: Telegram
    url: https://t.me/FarrelF
    weight: -40
    params:
      icon: brand-telegram