[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.80.0"
    TZ = "Asia/Jakarta"

[context.production]
    command = "hugo --gc --minify --enableGitInfo"
    [context.production.environment]
        HUGO_ENV = "production"

[context.split1]
    command = "hugo --gc --minify --enableGitInfo"
    [context.split1.environment]
        HUGO_ENV = "production"

[context.deploy-preview]
    command = "hugo --gc --minify --enableGitInfo --buildFuture -b ${DEPLOY_PRIME_URL}"

[context.branch-deploy]
    command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

    [plugin.inputs]
        debug = true

[[headers]]
    for = "/*"

    [headers.values]
        Cache-Control = "public, max-age=360, s-maxage=360, must-revalidate"
        Content-Security-Policy = [
            "img-src 'self' data: https://*.cloudfront.net https://cdn.statically.io https://cdn.jsdelivr.net https://*.gstatic.com https://*.disquscdn.com https://*.google.com https://*.disqus.com;",
            "font-src data: 'self' https://cdn.jsdelivr.net https://cdn.statically.io https://fonts.gstatic.com;",
            "connect-src 'self'; frame-src 'self' https://disqus.com https://*.disqus.com;",
            "object-src 'self'; frame-ancestors 'self';",
            "upgrade-insecure-requests; block-all-mixed-content;",
            "report-uri https://farrelf.report-uri.com/r/d/csp/enforce"
        ]
        Expect-CT = "max-age=604800, enforce, report-uri="https://farrelf.report-uri.com/r/d/ct/enforce""
        Feature-Policy = "camera https://*.disqus.com https://*.disquscdn.com; autoplay 'none'; usb 'none'; unsized-media 'none'"
        NEL = "{"report_to":"default","max_age":31536000,"include_subdomains":true}"
        Permissions-Policy = "gyroscope=(), microphone=(https://farrelf-blog.disqus.com https://*.disquscdn.com), vibrate=(), magnetometer=(), camera=(https://farrelf-blog.disqus.com https://*.disquscdn.com), midi=()"
        Referrer-Policy = "strict-origin-when-cross-origin"
        Report-To = "{"group":"default","max_age":31536000,"endpoints":[{"url":"https://farrelf.report-uri.com/a/d/g"}],"include_subdomains":true}"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-UA-Compatible = "IE=edge"
        X-XSS-Protection = "0"
