[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.82.0"
    TZ = "Asia/Jakarta"

[context.production]
    command = "rm static/robots_preview; hugo --minify --enableGitInfo"
    [context.production.environment]
        HUGO_ENV = "production"

[context.split1]
    command = "rm static/robots_preview; hugo --minify --enableGitInfo"
    [context.split1.environment]
        HUGO_ENV = "production"

[context.deploy-preview]
    command = "rm -rf static/*.txt static/*.xml static/google*.html static/_redirects; mv static/robots_preview static/robots.txt; hugo --gc --minify --enableGitInfo --config config.preview.yaml --buildFuture -b ${DEPLOY_PRIME_URL}"
    [context.deploy-preview.environment]
        HUGO_ENV = "staging"

[context.branch-deploy]
    command = "rm -rf static/*.txt static/*.xml static/google*.html static/_redirects; mv static/robots_preview static/robots.txt; hugo --gc --minify --config config.preview.yaml -b ${DEPLOY_PRIME_URL}"
    [context.branch-deploy.environment]
        HUGO_ENV = "staging"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

    [plugin.inputs]
        debug = true

[[headers]]
    for = "/*"

    [headers.values]
        Cache-Control = "public, max-age=180"
        Report-To = '''{
            "group": "default",
            "max_age": 31536000,
            "endpoints":[
                {"url": "https://farrelf.report-uri.com/a/d/g"}
            ],
            "include_subdomains": true
        }'''
        Content-Security-Policy = '''
        img-src 'self' data: https://*.cloudfront.net https://cdn.statically.io https://cdn.jsdelivr.net https://*.gstatic.com https://*.disquscdn.com https://*.google.com https://*.disqus.com;
        font-src data: 'self' https://cdn.jsdelivr.net https://cdn.statically.io https://*.cloudfront.net https://fonts.gstatic.com;
        connect-src 'self'; 
        frame-src 'self' https://disqus.com https://*.disqus.com;
        object-src 'self'; 
        frame-ancestors 'self';
        upgrade-insecure-requests; block-all-mixed-content;
        report-uri https://farrelf.report-uri.com/r/d/csp/enforce;
        report-to default;'''
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        Feature-Policy = "camera https://*.disqus.com https://*.disquscdn.com; autoplay 'none'; usb 'none'; gyroscope 'none'; vibrate 'none'; midi 'none'"
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Permissions-Policy = '''
        gyroscope=(), 
        usb=(), 
        autoplay=(), 
        microphone=("https://farrelf-blog.disqus.com" "https://*.disquscdn.com"), 
        vibrate=(), 
        magnetometer=(), 
        camera=("https://farrelf-blog.disqus.com" "https://*.disquscdn.com"), 
        midi=()'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-UA-Compatible = "IE=edge"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*/style.min.*.css"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Report-To = '''{
            "group": "default",
            "max_age": 31536000,
            "endpoints":[
                {"url": "https://farrelf.report-uri.com/a/d/g"}
            ],
            "include_subdomains": true
        }'''
        Content-Security-Policy = '''
        img-src 'self' data: https://*.cloudfront.net https://cdn.statically.io https://cdn.jsdelivr.net https://*.gstatic.com https://*.disquscdn.com https://*.google.com https://*.disqus.com;
        font-src data: 'self' https://cdn.jsdelivr.net https://cdn.statically.io https://*.cloudfront.net https://fonts.gstatic.com;
        connect-src 'self'; 
        frame-src 'self' https://disqus.com https://*.disqus.com;
        object-src 'self'; 
        frame-ancestors 'self';
        upgrade-insecure-requests; block-all-mixed-content;
        report-uri https://farrelf.report-uri.com/r/d/csp/enforce;
        report-to default;'''
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        Feature-Policy = "camera https://*.disqus.com https://*.disquscdn.com; autoplay 'none'; usb 'none'; gyroscope 'none'; vibrate 'none'; midi 'none'"
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Permissions-Policy = '''
        gyroscope=(), 
        usb=(), 
        autoplay=(), 
        microphone=("https://farrelf-blog.disqus.com" "https://*.disquscdn.com"), 
        vibrate=(), 
        magnetometer=(), 
        camera=("https://farrelf-blog.disqus.com" "https://*.disquscdn.com"), 
        midi=()'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-UA-Compatible = "IE=edge"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*/main.min.*.js"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Report-To = '''{
            "group": "default",
            "max_age": 31536000,
            "endpoints":[
                {"url": "https://farrelf.report-uri.com/a/d/g"}
            ],
            "include_subdomains": true
        }'''
        Content-Security-Policy = '''
        img-src 'self' data: https://*.cloudfront.net https://cdn.statically.io https://cdn.jsdelivr.net https://*.gstatic.com https://*.disquscdn.com https://*.google.com https://*.disqus.com;
        font-src data: 'self' https://cdn.jsdelivr.net https://cdn.statically.io https://*.cloudfront.net https://fonts.gstatic.com;
        connect-src 'self'; 
        frame-src 'self' https://disqus.com https://*.disqus.com;
        object-src 'self'; 
        frame-ancestors 'self';
        upgrade-insecure-requests; block-all-mixed-content;
        report-uri https://farrelf.report-uri.com/r/d/csp/enforce;
        report-to default;'''
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        Feature-Policy = "camera https://*.disqus.com https://*.disquscdn.com; autoplay 'none'; usb 'none'; gyroscope 'none'; vibrate 'none'; midi 'none'"
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Permissions-Policy = '''
        gyroscope=(), 
        usb=(), 
        autoplay=(), 
        microphone=("https://farrelf-blog.disqus.com" "https://*.disquscdn.com"), 
        vibrate=(), 
        magnetometer=(), 
        camera=("https://farrelf-blog.disqus.com" "https://*.disquscdn.com"), 
        midi=()'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-UA-Compatible = "IE=edge"
        X-XSS-Protection = "0"
