[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.91.2"
    GO_VERSION = "1.17.3"
    TZ = "Asia/Jakarta"

[context.production]
    command = "rm static/robots_preview; hugo --minify --gc"
    [context.production.environment]
        HUGO_ENV = "production"

[context.split1]
    command = "rm static/robots_preview; hugo --minify --gc"
    [context.split1.environment]
        HUGO_ENV = "production"

[context.deploy-preview]
    command = "rm -rf static/*.txt static/*.xml static/google*.html static/_redirects; mv static/robots_preview static/robots.txt; hugo --gc --minify --buildFuture -b ${DEPLOY_PRIME_URL}"
    [context.deploy-preview.environment]
        HUGO_ENV = "staging"

[context.branch-deploy]
    command = "rm -rf static/*.txt static/*.xml static/google*.html static/_redirects; mv static/robots_preview static/robots.txt; hugo --gc --minify -b ${DEPLOY_PRIME_URL}"
    [context.branch-deploy.environment]
        HUGO_ENV = "staging"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

    [plugin.inputs]
        debug = true

[[headers]]
    for = "/*"

    [headers.values]
        Cache-Control = "public, max-age=180"
        Report-To = '''{
            "group": "default",
            "max_age": 31536000,
            "endpoints":[
                {"url": "https://farrelf.report-uri.com/a/d/g"}
            ],
            "include_subdomains": true
        }'''
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        Feature-Policy = "camera https://giscus.app; autoplay 'none'; usb 'none'; gyroscope 'none'; vibrate 'none'; midi 'none'"
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Permissions-Policy = '''
        gyroscope=(), 
        usb=(), 
        autoplay=(), 
        microphone=("https://giscus.app"), 
        vibrate=(), 
        magnetometer=(), 
        camera=("https://giscus.app"), 
        midi=()'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-UA-Compatible = "IE=edge"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*/style.min.*.css"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Report-To = '''{
            "group": "default",
            "max_age": 31536000,
            "endpoints":[
                {"url": "https://farrelf.report-uri.com/a/d/g"}
            ],
            "include_subdomains": true
        }'''
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        Feature-Policy = "camera 'none'; autoplay 'none'; usb 'none'; gyroscope 'none'; vibrate 'none'; midi 'none'"
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Permissions-Policy = '''
        gyroscope=(), 
        usb=(), 
        autoplay=(), 
        microphone=(), 
        vibrate=(), 
        magnetometer=(), 
        camera=(), 
        midi=()'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-UA-Compatible = "IE=edge"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*/main.min.*.js"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Report-To = '''{
            "group": "default",
            "max_age": 31536000,
            "endpoints":[
                {"url": "https://farrelf.report-uri.com/a/d/g"}
            ],
            "include_subdomains": true
        }'''
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        Feature-Policy = "camera 'none'; autoplay 'none'; usb 'none'; gyroscope 'none'; vibrate 'none'; midi 'none'"
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Permissions-Policy = '''
        gyroscope=(), 
        usb=(), 
        autoplay=(), 
        microphone=(), 
        vibrate=(), 
        magnetometer=(), 
        camera=(), 
        midi=()'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.jpg"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "image/jpeg"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.jpeg"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "image/jpeg"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.png"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "image/png"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.apng"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "image/apng"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.gif"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "image/gif"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.webp"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "image/webp"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.svg"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "image/svg+xml"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.woff"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "font/woff"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"

[[headers]]
    for = "/*.woff2"

    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        Access-Control-Allow-Origin = "*"
        Access-Control-Expose-Headers = "*"
        Timing-Allow-Origin = "*"
        Content-Type = "font/woff2"
        Expect-CT = "max-age=604800, enforce, report-uri=\"https://farrelf.report-uri.com/r/d/ct/enforce\""
        NEL = '''{
            "report_to": "default",
            "max_age": 31536000,
            "include_subdomains": true
        }'''
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "0"
