CDN:
  Images:
    URL: https://cdn.statically.io/img/farrel.franqois.id/q=40,f=auto
  SVG:
    URL: https://cdn.statically.io/img/farrel.franqois.id
  JS:
    URL: https://cdn.statically.io/js/farrel.franqois.id
  CSS:
    URL: https://cdn.statically.io/css/farrel.franqois.id
  Fonts:
    URL: https://cdn.statically.io/css/farrel.franqois.id

arcio:
  # Check https://arc.io
  enabled: false
  widgetId: D1Tc1z8H

Counter:
  enabled: true
  Username: FarrelF
  utcOffset: 7
