CDN:
  Images:
    URL: https://cdn.statically.io/img/farrel.franqois.id/f=auto
  SVG:
    URL: https://cdn.statically.io/img/farrel.franqois.id
  JS:
    URL: https://cdn.statically.io/js/farrel.franqois.id
  CSS:
    URL: https://cdn.statically.io/css/farrel.franqois.id
  Fonts:
    URL: https://cdn.statically.io/css/farrel.franqois.id

arcio:
  # Check https://arc.io
  enabled: true
  widgetId: D1Tc1z8H

comments:
  enabled: true
  provider: giscus
  giscus:
    repo: FarrelF/Blog
    repoID: MDEwOlJlcG9zaXRvcnkzMzYxMTQzMzc=
    category: Komentar Blog
    categoryID: DIC_kwDOFAiyoc4B_M30
    mapping: pathname
    lightTheme: light
    darkTheme: dark_dimmed
    reactionsEnabled: 1
    emitMetadata: 1