cdn:
  images:
    url: https://cdn.statically.io/img/farrel.franqois.id/f=auto
    permalinks: false
  svg:
    url: https://cdn.statically.io/img/farrel.franqois.id
  js:
    url: https://cdn.statically.io/js/farrel.franqois.id
  css:
    url: https://cdn.statically.io/css/farrel.franqois.id
  fonts:
    url: https://cdn.statically.io/css/farrel.franqois.id

arcio:
  # Check https://arc.io
  enabled: false
  widgetId: D1Tc1z8H

counter:
  enabled: false
  username: FarrelF
  utcOffset: 7
