#[cdn.images]
#url = "https://cdn.statically.io/img/farrel.franqois.id/f=auto"
#permalinks = false
#
#[cdn.svg]
#url = "https://cdn.statically.io/img/farrel.franqois.id"
#
#[cdn.js]
#url = "https://cdn.statically.io/js/farrel.franqois.id"
#
#[cdn.css]
#url = "https://cdn.statically.io/css/farrel.franqois.id"
#
#[cdn.fonts]
#url = "https://cdn.statically.io/css/farrel.franqois.id"

[arcio]
enabled = true
widgetId = "D1Tc1z8H"

[counter]
enabled = false
username = "FarrelF"
utcOffset = 7

[umami]
enabled = false
hostURL = "https://analitik.franqois.id"
websiteID= "b4aac942-29c5-4f5e-8403-77d9c7eeda23"
