name: Testing Site
on:
  pull_request:
    branches:
      - drafts
      - main
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/LICENSE*"
      - "**/CONTRIBUTING.md"
      - "**/.gitignore"
      - "**/netlify.toml"
      - "config/development/**"
      - "**/archetypes/**"
      - "**/.markdownlint.*"

jobs:
  build:
    name: Build (Preview)
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Jakarta
      HUGO_ENV: staging

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Set up APT Mirror
      # GitHub Actions APT proxy is super unstable
      # See: https://github.com/actions/runner-images/issues/7048
      run: |
        printf 'http://azure.archive.ubuntu.com/ubuntu\tpriority:1\n' | sudo tee /etc/apt/mirrors.txt
        curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
        sudo sed -i 's/http:\/\/azure.archive.ubuntu.com\/ubuntu\//mirror+file:\/etc\/apt\/mirrors.txt/' /etc/apt/sources.list

    - name: Install All Locales and Other Packages
      run: |
        sudo sh -c 'apt update; apt install -y locales locales-all pigz'
        sudo update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
        sudo ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime

    - name: Setup Go
      env:
        GO_VERSION: stable
      uses: actions/setup-go@v7
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false

    - name: Setup Hugo Extended
      uses: ./.github/actions/setup-hugo
      with:
        hugo-version: latest
        verify-file: true
        is-extended: true
        is-with-deploy: false
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Dart Sass
      uses: ./.github/actions/setup-dart-sass
      with:
        dart-sass-version: latest
        is-musl: false
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify Installations
      run: |
        echo "Go: $(go version)"
        echo "Hugo: $(hugo version)"
        echo "Dart Sass: $(sass --version)"

    - name: Setup Hugo Resources Cache
      uses: actions/cache@v5
      with:
        path: ./resources
        key: v2-5-hugo-preview
        restore-keys: |
          - v2-5-hugo-preview

    - name: Setup Hugo Modules Cache
      uses: actions/cache@v5
      with:
        path: /tmp/hugo_cache_runner
        key: ${{ runner.os }}-hugo-modules-preview-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          - ${{ runner.os }}-hugo-modules-preview-${{ hashFiles('**/go.sum') }}

    - name: Building the Static Web (Preview)
      run: |
        rm -rf static/*.txt static/*.xml static/google*.html static/CNAME static/_redirects
        hugo --gc --buildFuture --environment staging -b https://$GITHUB_SHA-staging.farrelf.blog
        printf "SHORT_SHA=%s\n" ${GITHUB_SHA::7} >> $GITHUB_ENV

    - name: Compressing Static Web Files
      run: |
        # pigz -km -9 $(find public -iname '*.html' -o -iname '*.css' -o -iname '*.js' -o -iname '*.json' -o -iname '*.xml' -o -iname '*.svg' -o -iname '*.txt')
        # brotli -Zn $(find public -iname '*.html' -o -iname '*.css' -o -iname '*.js' -o -iname '*.json' -o -iname '*.xml' -o -iname '*.svg' -o -iname '*.txt')
        tar cvf - ./public | pigz -9 > files.tar.gz

    - name: Upload Output File to Artifact
      uses: actions/upload-artifact@v7
      with:
        name: preview-build-result-${{ env.SHORT_SHA }}
        path: files.tar.gz
        retention-days: 1

  deploy_to_bunny_net:
    name: Deploy to Bunny Storage (Preview)
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout the Code
      uses: actions/checkout@v7
    - name: Setup Environment Variable
      run: |
        printf "GITHUB_SHA=%s\n" ${GITHUB_SHA} >> $GITHUB_ENV
        printf "SHORT_SHA=%s\n" ${GITHUB_SHA::7} >> $GITHUB_ENV

    - name: Download Output File from Artifact
      uses: actions/download-artifact@v8
      with:
        name: preview-build-result-${{ env.SHORT_SHA }}

    - name: Setup Mise and Thumper
      uses: jdx/mise-action@v3
    - name: Decompressing Files
      run: |
        tar -xvzf files.tar.gz

    - name: Deploying to Bunny Storage
      run: thumper sync public ${{ secrets.BUNNY_PREVIEW_STORAGE_USERNAME }} --concurrency 8 --verbose
      env:
        THUMPER_KEY: "${{ secrets.BUNNY_PREVIEW_STORAGE_PASSWORD }}"

    - name: Activate Staging Environment
      run: |
        curl  -so /dev/null -w '%{http_code}\n' -H 'AccessKey: ${{ secrets.BUNNY_API_KEY }}' \
              -H 'content-type: application/json' \
              --data '{
                "ActionType": 4,
                "TriggerMatchingType": 1,
                "Enabled": true,
                "Guid": "${{ secrets.BUNNY_PREVIEW_EDGE_RULES_GUID }}",
                "OrderIndex": 7,
                "Description": "Block Request for Another Staging URL",
                "Triggers": [
                  {
                    "Type": 0,
                    "PatternMatchingType": 0,
                    "PatternMatches": [
                      "*://*-staging.farrelf.blog"
                    ]
                  },
                  {
                    "Type": 0,
                    "PatternMatchingType": 2,
                    "PatternMatches": [
                      "*://${{ env.GITHUB_SHA }}-staging.farrelf.blog",
                      "*://${{ env.SHORT_SHA }}-staging.farrelf.blog"
                    ]
                  }
                ]
              }' \
              https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULLZONE_ID }}/edgerules/addOrUpdate > http_output

        HTTP_CODE=$(cat http_output)
        rm http_output
        if [[ $HTTP_CODE -ge 200 && $HTTP_CODE -lt 300 ]]; then
            echo "Staging Environment has been successfully activated, you can visit one of following URL for preview changes"
            echo "- https://${{ env.SHORT_SHA }}-staging.farrelf.blog"
            echo "- https://${{ env.GITHUB_SHA }}-staging.farrelf.blog"
        else
            echo "Staging Environment activation failed, the error code: $HTTP_CODE"
            exit 1
        fi

  deploy_to_s3_compatible:
    name: Deploy to ${{ matrix.display_name }}
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - remote: cloudflare-r2
            display_name: Cloudflare R2
          - remote: backblaze-b2
            display_name: Backblaze B2
          - remote: bunny-s3-staging
            display_name: Bunny S3
    steps:
    - name: Setup Environment Variable
      run: printf "SHORT_SHA=%s\n" ${GITHUB_SHA::7} >> $GITHUB_ENV
    - name: Download Output File from Artifact
      uses: actions/download-artifact@v8
      with:
        name: preview-build-result-${{ env.SHORT_SHA }}

    - name: Decompressing Files
      run: |
        tar -xvzf files.tar.gz

    - name: Installing and Configuring Rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash
        mkdir -p ${HOME}/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > ${HOME}/.config/rclone/rclone.conf

    - name: Deploying to ${{ matrix.display_name }}
      env:
        RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
        S3_SERVICE: ${{ matrix.remote }}
      run: |
        rclone sync -v -P --stats-one-line --transfers=32 --checkers=32 --checksum ./public ${S3_SERVICE}:/${{ secrets.S3_PREVIEW_STORAGE_BUCKET }}
