name: Staging Site

on:
  pull_request:
    branches:
      - drafts
      - main
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/LICENSE*"
      - "**/CONTRIBUTING.md"
      - "**/.gitignore"
      - "**/netlify.toml"
      - "config/development/**"
      - "**/archetypes/**"
      - "**/.markdownlint.*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    with:
      environment: staging
      base-url: https://${{ github.sha }}-staging.farrelf.blog
      build-future: true
      artifact-name: staging-build-result-${{ github.sha }}
      resources-cache-key: v2-5-hugo-staging
      modules-cache-prefix: staging
      hugo-version: latest

  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: staging
      artifact-name: staging-build-result-${{ github.sha }}
      enable-preview-edge-rule: true
    secrets:
      s3-bucket: ${{ secrets.S3_PREVIEW_STORAGE_BUCKET }}
      bunny-storage-username: ${{ secrets.BUNNY_PREVIEW_STORAGE_USERNAME }}
      bunny-storage-password: ${{ secrets.BUNNY_PREVIEW_STORAGE_PASSWORD }}
      rclone-config: ${{ secrets.RCLONE_CONFIG }}
      rclone-config-pass: ${{ secrets.RCLONE_CONFIG_PASS }}
      bunny-api-key: ${{ secrets.BUNNY_API_KEY }}
      bunny-pullzone-id: ${{ secrets.BUNNY_PULLZONE_ID }}
      bunny-preview-edge-rules-guid: ${{ secrets.BUNNY_PREVIEW_EDGE_RULES_GUID }}
